#!/bin/sh

version=$(cat /etc/debian_version)

case $version in
  9.*) echo "OK: Debian version $version"; exit 0 ;;
  8.*) echo "WARNING: Debian version $version"; exit 1 ;;
  *) echo "CRITICAL: Debian version $version"; exit 2 ;;
esac
