#!/bin/sh

if ip -4 a | grep -q 'scope global'; then
	if iptables -nL | grep -q REJECT; then
		OUT="ipv4 firewall ok"
	elif iptables-legacy -nL | grep -q REJECT; then
		OUT="ipv4 firewall ok"
	else
		OUT="ipv4 firewall missing"
		BAD=1
	fi
else
	OUT="no ipv4 address present"
	BAD=1
fi

if ip -6 a | grep -q 'scope global'; then
	if ip6tables -nL | grep -q REJECT; then
		OUT="$OUT, ipv6 firewall ok"
	elif ip6tables-legacy -nL | grep -q REJECT; then
		OUT="$OUT, ipv6 firewall ok"
	else
		OUT="$OUT, ipv6 firewall missing"
		BAD=1
	fi
else
	OUT="$OUT, no ipv6 address present"
fi

if [ "$BAD" ]; then
	echo "FIREWALL CRITICAL: $OUT"
	exit 2
else
	echo "FIREWALL OK: $OUT"
fi
