#!/bin/sh

for f in /var/mail/*; do
	test -f "$f" || continue
	# don't care about empty files
	test -s "$f" && OUT="${OUT:+$OUT; }$(stat -c "%n (%s bytes, %z)" $f)"
done

if [ "$OUT" ]; then
	echo Local mailboxes: $OUT
	exit 1
fi

echo "No local mailboxes"
exit 0
