#!/usr/bin/env python3

import argparse
import configparser
import shutil
import subprocess
import sys

colors = {
        'white': "\x0300",
        'black': "\x0301",
        'blue': "\x0302",
        'green': "\x0303",
        'lightred': "\x0304",
        'red': "\x0305",
        'magenta': "\x0306",
        'orange': "\x0307",
        'yellow': "\x0308",
        'lightgreen': "\x0309",
        'cyan': "\x0310",
        'lightcyan': "\x0311",
        'lightblue': "\x0312",
        'lightmagenta': "\x0313",
        'grey': "\x0314",
        'lightgrey': "\x0315",
        'bold': "\x02",
        'underline': "\x1f",
        'reverse': "\x16",
        'reset': "\x0f",
        }

def main(argv):
    configreader = configparser.ConfigParser()
    configreader.read('/etc/oftc/nagios/nagios-irker.ini')
    config = configreader['config']

    parser = argparse.ArgumentParser(add_help=False)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('-h', '--host', action='store_const', const='host', dest='mode')
    group.add_argument('-s', '--service', action='store_const', const='service', dest='mode')
    parser.add_argument('vars', nargs='*')

    args = parser.parse_args(argv[1:])

    params = {}
    for item in args.vars:
        key, _, value = item.partition('=')
        params[key] = value

    template = config[f"{args.mode}-template"]
    colors['state'] = colors[config[params['state']]]

    result = template.format(params=params, colors=colors) + '\n'

    irk = shutil.which('irk')
    subprocess.run([irk, config['target'], '-'], input=result, text=True)

    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
