#!/bin/sh

RO=$(mount | grep -v -e tmpfs -e /boot | grep -w '(ro')

if [ "$RO" ]; then
	# no quotes here to have multiple results on one line
	echo CRITICAL: Filesystems mounted read-only: $RO
	exit 2
fi

echo OK: No filesystems mounted read-only
exit 0
