#!/bin/bash

# Copyright (C) 2015 Christoph Berg <myon@oftc.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -u

if [ "${1:-}" = 'config' ]; then
	cat <<EOF
graph_title ircd memory
graph_vlabel bytes
graph_category OFTC
hybrid_rss.label hybrid RSS
hybrid_vsz.label hybrid VSZ
testnet-hybrid_rss.label testnet RSS
testnet-hybrid_vsz.label testnet VSZ
EOF
	exit 0
fi

for ircd in hybrid testnet-hybrid; do
	pid=$(cat ~oftc/$ircd/var/ircd.pid)
	for thing in rss vsz; do
		kilobyes=$(ps -o$thing h $pid)
		bytes=$((kilobyes * 1024))
		echo ${ircd}_$thing.value $bytes
	done
done
