#!/bin/bash

# Copyright TJ Fontaine <tjfontaine@oftc.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# minor updates by Peter Palfrader <peter@palfrader.org>

PIDFILE=/home/oftc/ircservices/services/var/run/services.pid

if [ "$1" = "autoconf" ]; then
  echo yes
  exit 0
fi

if [ "$1" = "config" ]; then
  echo 'graph_title Services Memory Usage'
  echo 'graph_args -l 0'
  echo 'graph_vlabel usage'
  echo 'graph_info This graph shows memory usage of services'
  echo 'vsz.label VSZ'
  echo 'vsz.cdef vsz,1024,*'
  echo 'vsz.draw AREA'
  echo 'vsz.info Virtual memory size'
  echo 'rss.label RSS'
  echo 'rss.cdef rss,1024,*'
  echo 'rss.draw AREA'
  echo 'rss.info Resident memory size'
  exit 0
fi


[ -e "$PIDFILE" ] || exit 1
PID=`cat "$PIDFILE"`
[ -n "$PID" ] || exit 1
kill -0 "$PID" || exit 1

INFO=`ps h -o rss,vsz -p "$PID"`

counter="0"
for i in $INFO
do
  case $counter in
  "0")
    echo "rss.value $i"
    counter="1"
    ;;
  "1")
    echo "vsz.value $i"
    counter="2"
    ;;
  esac
done
