#!/bin/sh

set -eu

cd /var/lib/mailman/data

# most of oftc-admin-private is spam, do not trigger alerts
nfiles=$(find . -name heldmsg-\* -mmin +5 -not -name heldmsg-oftc-admin-private-\* | wc -l)

if [ $nfiles = 0 ]; then
	echo "No messages awaiting moderation"
	exit 0
fi

oldest=$(ls -rt heldmsg-* | head -1)
mtime=$(stat -c %Y $oldest)
now=$(date +%s)
age=$((now - mtime))

stats=$(find . -name heldmsg-\* -mmin +5 -not -name heldmsg-oftc-admin-private-\* | sed -e 's/.*heldmsg-//' -e 's/-[0-9]*.pck//' | sort | uniq -c | sort -nr | xargs)
oldtime=$(stat -c %y $oldest | sed -e 's/\..*//')

echo "$nfiles msgs queued: $stats, oldest is from $oldtime"
if [ $nfiles -gt 10 ] || [ $age -gt $((3 * 86400)) ]; then
	exit 2
else
	exit 1
fi
