#!/bin/bash

# Copyright 2007 Peter Palfrader <peter@palfrader.org>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# create a backup of the services database, excluding the log (transaction/write ahead logs) directory
# those are handled separately

set -e

umask 077

HOST=`hostname`
CLUSTER="ircservices"
VERSION="8.3"
DATE=$(date "+%Y%m%d")
PORT=5433

LABEL="$DATE-$HOST-$CLUSTER-$VERSION-backup"
ID=`sudo -u postgres psql -p "$PORT" --tuples-only --command "SELECT pg_start_backup('$LABEL');"`
trap "sudo -u postgres psql -q -p '$PORT' --command 'SELECT pg_stop_backup();'" exit
ID=`echo $ID | sed -e 's/[^a-zA-Z0-9]/_/g'`

cd /var/lib/postgresql
TARBALL="$LABEL-$ID.tar.bz2"
if tar cjf "$TARBALL" --exclude "$VERSION/$CLUSTER/pg_xlog" "$VERSION/$CLUSTER"; then
	:  # all went well
else
	if [ "$?" = 1 ]; then
		echo "Ignoring tar exit code of 1" >&2
	else
		echo "Dying because tar exited with an exit code not in {0, 1}" >&2
		exit 1
	fi
fi

chown postgres: "$TARBALL"
sudo -u postgres scp "$TARBALL" backup:ircservices-tarballs/
rm "$TARBALL"
