#!/bin/bash

# Copyright 2007 Peter Palfrader <peter@palfrader.org>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Sync the postgres pg_xlog directory every few minutes to the backup host.

trap "kill %%; exit 1" SIGTERM

LOGTAG="xlogsync"
MYHOSTNAME=`hostname`

errorcount=0
cd /var/lib/postgresql/8.3/ircservices || exit 1

logger -t "$LOGTAG" "Starting"
while :; do
	rsync -raz --delete-after --exclude archive_status pg_xlog/ backup:"pg_xlog-$MYHOSTNAME"
	err="$?"
	if [ "$err" != 0 ]; then
		errorcount=$(( errorcount + 1 ))
		logger -t "$LOGTAG" "Syncing pg_xlog/ failed for $errorcount consecutive tries."
	else
		errorcount=0
		logger -t "$LOGTAG" "Synced pg_xlog/ successfully."
	fi
	sleep 5m
done &
wait $!

