#!/usr/bin/ruby

require 'net/IRC'
require 'yaml'

OPER_USER = ''
OPER_PASS = ''
NICK = 'oftc-geoip-bot'
USER = 'oftc-geoip-bot'
GCOS = 'OFTC GeoIP Collector'
SERVER = 'ircs.oftc.net'
PORT = '9999'
PASSWORD = ''
USESSL = true

def next_link(sender, source, params)
  $links << params[1]  
end

def next_who(sender, source, params)
  $clients << {
    'address' => params[3],
    'server' => params[4]
  }
end

def end_links(sender, source, params)
  $clients = []
  sender.send('WHO +In *')
end

def end_who(sender, source, params)
  time = Time.now
  filename = "data/irc-data-%d.yaml" % time.to_i
  f = File.new(filename, 'w')
  data = {
    'links' => $links,
    'clients' => $clients
  }
  f.puts data.to_yaml
  f.close
  puts "Created file %s" % filename
end

def motd(sender, source, params)
  puts "%s is connected" % sender.nickname
  sender.send("OPER %s %s" % [OPER_USER, OPER_PASS])
  get_data(sender)
end

def ping_timer(sender, source, params)
  get_data(sender)
end

def get_data(sender)
  $links = []
  sender.send('LINKS')
end

$conn = nil

inthandler = proc{
  puts "^C pressed"
  $conn.each do |x|
    x.quit('SIGINT')
  end
}

trap("SIGINT", inthandler)

$conn = IRC.new(NICK, USER, GCOS)
$conn.add_handler('376', :motd)
$conn.add_handler('PING', :ping_timer)
$conn.add_handler('364', :next_link)
$conn.add_handler('365', :end_links)
$conn.add_handler('352', :next_who)
$conn.add_handler('315', :end_who)
$conn.connect(SERVER, PORT, PASSWORD, USESSL)
$conn.run()
