#!/usr/bin/python
# Copyright (C) 2007 Luca Filipozzi
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.

import sys, string, radix

ip2region = radix.Radix()
f = open(sys.argv[1])
for line in f:
  cidr,region = line.strip().split(' ')
  ip2region.add(cidr).data["region"] = region
f.close()

rval = 0
for line in sys.stdin:
  cidr,region = line.strip().split()
  rnode = ip2region.search_best(cidr)
  if rnode:
    if rnode.data["region"] != region:
      print "%s %s != %s" % (cidr, region, rnode.data["region"])
      rval = 1
  else:
    print "%s %s not found!!!" % (cidr, region)
    rval = 1
sys.exit(rval)

# vim: set ts=2 sw=2 et si:
