#!/usr/bin/python

import sys, string, radix

rtree = radix.Radix()
for line in sys.stdin:
    cidr,region = line.strip().split(' ')
    rtree.add(cidr).data["region"] = region
for rnode in rtree:
    print rnode.prefix, rnode.data["region"]

# vim: set ts=4 sw=4 et:
