#! /bin/sh

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="oftcdns Daemon"
NAME=oftcdns
DAEMON=/usr/bin/twistd2.3
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/var/run/$NAME.pid
PYTHONPATH=/usr/local/lib/python2.3/site-packages
RUNDIR=/var/local/$NAME
PYTHONFILE=$PYTHONPATH/$NAME/$NAME.tac

export PYTHONPATH

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Start the daemon.
d_start() {
  start-stop-daemon --start --quiet --exec $DAEMON -- \
    --pidfile=$PIDFILE --rundir=$RUNDIR --python=$PYTHONFILE \
    --syslog --prefix=$NAME --no_save
}

# Stop the daemon.
d_stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
}

case "$1" in
  start)
    echo -n "Starting $DESC: $NAME"
    d_start
    echo "."
    ;;
  stop)
    echo -n "Stopping $DESC: $NAME"
    d_stop
    echo "."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: $NAME"
    d_stop
    sleep 1
    d_start
    echo "."
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
# vim: set ts=2 sw=2 et:
